# Generated by Django 4.2.5 on 2023-09-08 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('ScName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ScPrincipal', models.CharField(max_length=100)),
                ('ScLocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=100)),
                ('ScName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
    ]
